In [2]:
## Notebook env: seq_trblsht (seq_trblsht kernel)
## This notebook is used to analyze the fraction of reads that map to the guide region in GEM1 of the CRISPRa library

In [ ]:
%%bash
cd /home/ssobti/projects/heterogeneity_brian/output_data/CRISPRa_repeat_screen/low_guides_trblsht/STAR_guide_reads_alignment
nohup STAR --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat --runThreadN 16 --genomeDir /home/genomes/hg38/star_hg38 --readFilesIn /home/ssobti/projects/heterogeneity_brian/data/072623_MD231_CRISPRa_repeat_screen/BWHG37/SL424_S3_L004_R2_001.fastq.gz --outFileNamePrefix SL424_R2_all_reads_no_trim &

## not run
%%bash
cd /home/ssobti/projects/heterogeneity_brian/output_data/CRISPRa_repeat_screen/low_guides_trblsht/STAR_guide_reads_alignment
samtools index --threads 16 SL424_R2_all_reads_no_trimAligned.sortedByCoord.out.bam SL424_R2_all_reads_no_trimAligned.sortedByCoord.out.bai

## not run
%%bash
cd /home/ssobti/projects/heterogeneity_brian/output_data/CRISPRa_repeat_screen/low_guides_trblsht/STAR_guide_reads_alignment
nohup bedtools multicov -bams SL424_R2_all_reads_no_trimAligned.sortedByCoord.out.bam -bed /home/genomes/hg38/star_hg38/Homo_sapiens.GRCh38.99.gtf > SL424_R2_all_reads_no_trim_bedtools.txt &

In [ ]:
%%bash
cd /home/ssobti/projects/heterogeneity_brian/output_data/CRISPRa_repeat_screen/low_guides_trblsht/STAR_guide_reads_alignment
nohup htseq-count -n 16 -f bam -s yes -i gene_id SL424_R2_all_reads_no_trimAligned.sortedByCoord.out.bam /home/genomes/hg38/star_hg38/Homo_sapiens.GRCh38.99.gtf > SL424_R2_all_reads_no_trim_HTSeq_count.txt &

In [84]:
## load in bed file gene counts from reads
import pandas as pd
import mygene as mg

path = '/home/ssobti/projects/heterogeneity_brian/output_data/CRISPRa_repeat_screen/low_guides_trblsht/STAR_guide_reads_alignment/'
read_counts = pd.read_csv(path + 'SL424_R2_all_reads_no_trim_HTSeq_count.txt', sep='\t', names = ['gene', 'count'])
read_counts.sort_values(by='count', ascending=False, inplace=True)
read_counts

                         gene     count
60680  __alignment_not_unique  84789687
60676            __no_feature  71026957
60677             __ambiguous   5641588
21453         ENSG00000211459   2100940
21417         ENSG00000210082   1854876
...                       ...       ...
28556         ENSG00000229190         0
28557         ENSG00000229191         0
28558         ENSG00000229192         0
28559         ENSG00000229195         0
30340         ENSG00000231794         0

[60681 rows x 2 columns]

In [85]:
remove_rows = ['__alignment_not_unique', '__no_feature', '__ambiguous']
read_counts = read_counts[~read_counts['gene'].isin(remove_rows)].reset_index()
read_counts

       index             gene    count
0      21453  ENSG00000211459  2100940
1      21417  ENSG00000210082  1854876
2       1315  ENSG00000075624   398501
3       6598  ENSG00000132507   359221
4      17941  ENSG00000198938   324730
...      ...              ...      ...
60673  28556  ENSG00000229190        0
60674  28557  ENSG00000229191        0
60675  28558  ENSG00000229192        0
60676  28559  ENSG00000229195        0
60677  30340  ENSG00000231794        0

[60678 rows x 3 columns]

In [82]:
## convert ENSEMBL IDs to gene symbols
import mygene as mg
mg = mygene.MyGeneInfo()
gene_symbols = mg.querymany(read_counts['gene'].tolist(), scopes='ensembl.gene', fields = ['symbol'], species = 'human')
gene_symbols = [gene['symbol'] if 'symbol' in gene.keys() else 'NA' for gene in gene_symbols]

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-20000...done.
querying 20001-21000...done.
querying 21001-22000...done.
querying 22001-23000...done.
querying 23001-24000...done.
querying 24001-25000...done.
querying 25001-26000...done.
querying 26001-27000...done.
querying 27001-28000...done.
querying 28001-29000...done.
querying 29001-30000...done.
querying 30001-31000...done.
querying 31001-32000...done.
querying 32001-33000...done.
querying 33001-34000...done.
querying 34001-35000...done.
querying 35001-36000...done.
querying 36001-37000...done.
querying 37001-38000...done.
querying 38001-39000...done.
querying 39001-40000...done.
querying 40001-41000...done.
querying 41001-42000...done.
querying 42001-43000...done.
querying 43001-44000...done.
querying 44001-45000...done.
querying 45001-46000...done.
querying 46001-47000...done.
querying 47001-48000...done.
querying 48001-49000...done.
querying 49001-50000...done.
querying 50001-51000...done.
querying 51001-52000...done.
querying 52001-53000...done.
querying 53001-54000...done.
querying 54001-55000...done.
querying 55001-56000...done.
querying 56001-57000...done.
querying 57001-58000...done.
querying 58001-59000...done.
querying 59001-60000...done.
querying 60001-60678...done.
Finished.
267 input query terms found no hit:
	['ENSG00000254615', 'ENSG00000130723', 'ENSG00000239665', 'ENSG00000205485', 'ENSG00000112096', 'ENS
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [87]:
## adding gene symbols
read_counts['symbol'] = gene_symbols
read_counts[0:30]

    index             gene    count  symbol
0   21453  ENSG00000211459  2100940    RNR1
1   21417  ENSG00000210082  1854876    RNR2
2    1315  ENSG00000075624   398501    ACTB
3    6598  ENSG00000132507   359221   EIF5A
4   17941  ENSG00000198938   324730    COX3
5    7539  ENSG00000137818   315297   RPLP1
6   17805  ENSG00000198695   276649     ND6
7   17572  ENSG00000197956   265503  S100A6
8   39796  ENSG00000251562   232729  MALAT1
9    9263  ENSG00000149925   231729   ALDOA
10  14990  ENSG00000181163   201603    NPM1
11  21433  ENSG00000210184   195655   TRNS2
12   3492  ENSG00000108107   166608   RPL28
13  10443  ENSG00000160213   151362    CSTB
14   8290  ENSG00000142937   142812    RPS8
15  37366  ENSG00000245532   141355   NEAT1
16  16238  ENSG00000186468   137159   RPS23
17  17848  ENSG00000198786   134699     ND5
18  17911  ENSG00000198888   128368     ND1
19  17882  ENSG00000198840   125019     ND3
20    452  ENSG00000026025   124809     VIM
21   1718  ENSG00000087086   109843     FTL
22   3949  ENSG00000111775   109196  COX6A1
23  22075  ENSG00000212907   108345    ND4L
24   5611  ENSG00000125148   106854    MT2A
25  17909  ENSG00000198886   105855     ND4
26   5805  ENSG00000126261    95559    UBA2
27    767  ENSG00000057019    86595  DCBLD2
28  14123  ENSG00000176731    86114    RBIS
29   3913  ENSG00000111640    85755   GAPDH